spring.application.name=Ecommerce


spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=CustomerDB

spring.data.mongodb.uri=mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@localhost:27017/CustomerDB?authSource=admin
