server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: root
    password: 1233321
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect #Postgre
application:
  config:
    product-url: http://localhost:8050/api/v1/products
    customer-url: http://localhost:8090/api/v1/customer
    payment-url: http://localhost:8070/api/v1/payments